// Copies contract ABIs from the Foundry build output into typed TS modules.
// Usage (from apps/web, after `forge build` in contracts/): bun run abi
import { existsSync } from "node:fs"
import { join } from "node:path"

const root = join(import.meta.dir, "..")
const outDir = join(root, "../../contracts/out")
const abiDir = join(root, "src/lib/abi")

const names = ["BondToken", "DiscountOracle", "InvoiceMarket", "MaturitySettlement"]
const written: string[] = []

for (const name of names) {
  const artifact = join(outDir, `${name}.sol`, `${name}.json`)
  if (!existsSync(artifact)) {
    console.warn(`skip ${name}: ${artifact} not found (contract not built yet?)`)
    continue
  }
  const { abi } = await Bun.file(artifact).json()
  const ident = name[0].toLowerCase() + name.slice(1)
  const file = join(abiDir, `${ident}.ts`)
  const header = `// Generated by scripts/abi.ts from contracts/out/${name}.sol/${name}.json. Do not edit.\n`
  await Bun.write(
    file,
    `${header}export const ${ident}Abi = ${JSON.stringify(abi, null, 2)} as const\n`,
  )
  written.push(file)
}

if (written.length) {
  Bun.spawnSync(["bunx", "biome", "format", "--write", ...written], { stdout: "inherit" })
  console.info(`wrote ${written.length} ABI module(s) to src/lib/abi`)
}
