// Generated by scripts/abi.ts from contracts/out/DiscountOracle.sol/DiscountOracle.json. Do not edit.
export const discountOracleAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "signer_",
        type: "address",
        internalType: "address",
      },
      {
        name: "owner_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "MAX_RATE_BPS",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "QUOTE_TYPEHASH",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "consume",
    inputs: [
      {
        name: "q",
        type: "tuple",
        internalType: "struct DiscountOracle.Quote",
        components: [
          {
            name: "invoiceId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "issuer",
            type: "address",
            internalType: "address",
          },
          {
            name: "faceValue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maturity",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "discountRateBps",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "validUntil",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "nonce",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
      {
        name: "signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "consumer",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "eip712Domain",
    inputs: [],
    outputs: [
      {
        name: "fields",
        type: "bytes1",
        internalType: "bytes1",
      },
      {
        name: "name",
        type: "string",
        internalType: "string",
      },
      {
        name: "version",
        type: "string",
        internalType: "string",
      },
      {
        name: "chainId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "verifyingContract",
        type: "address",
        internalType: "address",
      },
      {
        name: "salt",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "extensions",
        type: "uint256[]",
        internalType: "uint256[]",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hashQuote",
    inputs: [
      {
        name: "q",
        type: "tuple",
        internalType: "struct DiscountOracle.Quote",
        components: [
          {
            name: "invoiceId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "issuer",
            type: "address",
            internalType: "address",
          },
          {
            name: "faceValue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maturity",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "discountRateBps",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "validUntil",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "nonce",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nonceUsed",
    inputs: [
      {
        name: "nonce",
        type: "uint64",
        internalType: "uint64",
      },
    ],
    outputs: [
      {
        name: "used",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setConsumer",
    inputs: [
      {
        name: "consumer_",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSigner",
    inputs: [
      {
        name: "signer_",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "signer",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "newOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "verify",
    inputs: [
      {
        name: "q",
        type: "tuple",
        internalType: "struct DiscountOracle.Quote",
        components: [
          {
            name: "invoiceId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "issuer",
            type: "address",
            internalType: "address",
          },
          {
            name: "faceValue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maturity",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "discountRateBps",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "validUntil",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "nonce",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
      {
        name: "signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "ConsumerChanged",
    inputs: [
      {
        name: "consumer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EIP712DomainChanged",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "QuoteConsumed",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "discountRateBps",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "nonce",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SignerChanged",
    inputs: [
      {
        name: "signer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "BadSigner",
    inputs: [
      {
        name: "recovered",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ECDSAInvalidSignature",
    inputs: [],
  },
  {
    type: "error",
    name: "ECDSAInvalidSignatureLength",
    inputs: [
      {
        name: "length",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "ECDSAInvalidSignatureS",
    inputs: [
      {
        name: "s",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "InvalidShortString",
    inputs: [],
  },
  {
    type: "error",
    name: "NonceUsed",
    inputs: [
      {
        name: "nonce",
        type: "uint64",
        internalType: "uint64",
      },
    ],
  },
  {
    type: "error",
    name: "NotConsumer",
    inputs: [
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "QuoteExpired",
    inputs: [
      {
        name: "validUntil",
        type: "uint64",
        internalType: "uint64",
      },
    ],
  },
  {
    type: "error",
    name: "RateTooHigh",
    inputs: [
      {
        name: "rateBps",
        type: "uint16",
        internalType: "uint16",
      },
    ],
  },
  {
    type: "error",
    name: "StringTooLong",
    inputs: [
      {
        name: "str",
        type: "string",
        internalType: "string",
      },
    ],
  },
] as const
