// Generated by scripts/abi.ts from contracts/out/InvoiceMarket.sol/InvoiceMarket.json. Do not edit.
export const invoiceMarketAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "usdc_",
        type: "address",
        internalType: "contract IERC20",
      },
      {
        name: "oracle_",
        type: "address",
        internalType: "contract DiscountOracle",
      },
      {
        name: "complianceOperator_",
        type: "address",
        internalType: "address",
      },
      {
        name: "treasury_",
        type: "address",
        internalType: "address",
      },
      {
        name: "owner_",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BPS",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_FEE_BPS",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "asks",
    inputs: [
      {
        name: "askId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "maker",
        type: "address",
        internalType: "address",
      },
      {
        name: "units",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "priceBps",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "bondOf",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract BondToken",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyPrimary",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "units",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelAsk",
    inputs: [
      {
        name: "askId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "complianceOperator",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeBps",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fillAsk",
    inputs: [
      {
        name: "askId",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "units",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "grantBondRole",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "role",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "invoiceIds",
    inputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "listInvoice",
    inputs: [
      {
        name: "name",
        type: "string",
        internalType: "string",
      },
      {
        name: "symbol",
        type: "string",
        internalType: "string",
      },
      {
        name: "q",
        type: "tuple",
        internalType: "struct DiscountOracle.Quote",
        components: [
          {
            name: "invoiceId",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "issuer",
            type: "address",
            internalType: "address",
          },
          {
            name: "faceValue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "maturity",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "discountRateBps",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "validUntil",
            type: "uint64",
            internalType: "uint64",
          },
          {
            name: "nonce",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
      {
        name: "signature",
        type: "bytes",
        internalType: "bytes",
      },
    ],
    outputs: [
      {
        name: "bond",
        type: "address",
        internalType: "contract BondToken",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "listing",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct InvoiceMarket.Listing",
        components: [
          {
            name: "bond",
            type: "address",
            internalType: "contract BondToken",
          },
          {
            name: "issuer",
            type: "address",
            internalType: "address",
          },
          {
            name: "faceValue",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "discountRateBps",
            type: "uint16",
            internalType: "uint16",
          },
          {
            name: "maturity",
            type: "uint64",
            internalType: "uint64",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "listingCount",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "makeAsk",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "units",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "priceBps",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "askId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "nextAskId",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "oracle",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract DiscountOracle",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "primaryCost",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "units",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeBondRole",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "role",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setComplianceOperator",
    inputs: [
      {
        name: "operator",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFee",
    inputs: [
      {
        name: "feeBps_",
        type: "uint16",
        internalType: "uint16",
      },
      {
        name: "treasury_",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSettlement",
    inputs: [
      {
        name: "settlement_",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "settlement",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [
      {
        name: "newOwner",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IERC20",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AskCancelled",
    inputs: [
      {
        name: "askId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AskFilled",
    inputs: [
      {
        name: "askId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "taker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "units",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "paid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "fee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AskMade",
    inputs: [
      {
        name: "askId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "invoiceId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "maker",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "units",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "priceBps",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ComplianceOperatorChanged",
    inputs: [
      {
        name: "operator",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FeeChanged",
    inputs: [
      {
        name: "feeBps",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "treasury",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceListed",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "bond",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "issuer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "faceValue",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "discountRateBps",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "maturity",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PrimaryFunded",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "buyer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "units",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "paid",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "fee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SettlementChanged",
    inputs: [
      {
        name: "settlement",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AlreadyListed",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "FeeTooHigh",
    inputs: [
      {
        name: "feeBps",
        type: "uint16",
        internalType: "uint16",
      },
    ],
  },
  {
    type: "error",
    name: "FundingClosed",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "InsufficientUnits",
    inputs: [
      {
        name: "requested",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "available",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NotMaker",
    inputs: [
      {
        name: "askId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "NotQuotedIssuer",
    inputs: [
      {
        name: "quoted",
        type: "address",
        internalType: "address",
      },
      {
        name: "caller",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [
      {
        name: "owner",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [
      {
        name: "account",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ReentrancyGuardReentrantCall",
    inputs: [],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "TreasuryRequired",
    inputs: [],
  },
  {
    type: "error",
    name: "UnknownAsk",
    inputs: [
      {
        name: "askId",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
  {
    type: "error",
    name: "UnknownInvoice",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAmount",
    inputs: [],
  },
] as const
