// Generated by scripts/abi.ts from contracts/out/MaturitySettlement.sol/MaturitySettlement.json. Do not edit.
export const maturitySettlementAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "usdc_",
        type: "address",
        internalType: "contract IERC20",
      },
      {
        name: "market_",
        type: "address",
        internalType: "contract InvoiceMarket",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claim",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimable",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "holder",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "market",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract InvoiceMarket",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "registerRepayment",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "repayments",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "amount",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "supplySnapshot",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "settled",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "settle",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "usdc",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IERC20",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Claimed",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "holder",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "units",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "payout",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RepaymentRegistered",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "payer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "total",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Settled",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        indexed: true,
        internalType: "bytes32",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "supplySnapshot",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokenAssociated",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "AlreadySettled",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "AssociationFailed",
    inputs: [
      {
        name: "responseCode",
        type: "int64",
        internalType: "int64",
      },
    ],
  },
  {
    type: "error",
    name: "NotMatured",
    inputs: [
      {
        name: "maturity",
        type: "uint64",
        internalType: "uint64",
      },
    ],
  },
  {
    type: "error",
    name: "NotSettled",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "NothingRepaid",
    inputs: [
      {
        name: "invoiceId",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
  },
  {
    type: "error",
    name: "NothingToClaim",
    inputs: [
      {
        name: "holder",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ReentrancyGuardReentrantCall",
    inputs: [],
  },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [
      {
        name: "token",
        type: "address",
        internalType: "address",
      },
    ],
  },
  {
    type: "error",
    name: "ZeroAmount",
    inputs: [],
  },
] as const
